[server]
# Disable file watcher to avoid inotify limit issues
runOnSave = false
fileWatcherType = "none"

[client]
# Disable automatic script reruns
toolbarMode = "viewer"

[runner]
# Disable magic commands and fast reruns
magicEnabled = false
fastReruns = false
